server:
  port: 0
spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://localhost:3306/micro_db
    username: root
    password: kafamysql
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
