server:
  port: 8761

spring:
  application:
    name: service-registry

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: false #Eureka kendini başka bir Eureka'ya kaydetmez
    fetch-registry: false #Eureka diğer servisleri çekmez, sadece client kayıtlarını kabul eder
  server:
    wait-time-in-ms-when-sync-empty: 0
  instance:
    hostname: localhost #discovery için hostname belirtiyoruz
# eureka.instance.prefer-ip-address: true -->>    prod
