server: # Server configuration
  port: 8080

spring: # Application name
  application:
    name: api-gateway
  cloud: # Spring Cloud Gateway configuration
    gateway:
      discovery: # enable discovery-based route generation (auto create routes for services)
        locator:
          enabled: true # Auto-create routes from Eureka services
          lower-case-service-id: true # Use lowercase service names in URLs
      globalcors: # Global CORS configuration (handled by CorsConfig)
        cors-configurations:
          '[/**]':
            allowedOriginPatterns: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: true

eureka: # Eureka client configuration
  client:
    register-with-eureka: true # Register gateway with Eureka
    fetch-registry: true
    registry-fetch-interval-seconds: 30 # How often to fetch registry
    service-url: # point to your Eureka server
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    prefer-ip-address: true # Use IP address instead of hostname
    instance-id: ${spring.application.name}:${server.port} # Instance ID format
