# Configuration for API Gateway
server:
  port: 8080  # Gateway port

# Enable discovery-based routing so gateway forwards to discovered services
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true  # Enable service discovery for routes
          lower-case-service-id: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka  # Eureka Server URL
    fetch-registry: true
    register-with-eureka: true
    registry-fetch-interval-seconds: 30          # How often to fetch registry
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30
