server: # Server configuration
  port: 8761

spring: # Application name
  application:
    name: eureka-server
  security: # Security credentials (for clients to connect)
    user:
      name: eureka
      password: eureka123

eureka: # Eureka server configuration
  instance:
    hostname: localhost
  client:
    register-with-eureka: false # Disable self-registration for single server
    fetch-registry: false
    service-url: # Service URL with basic auth credentials
      defaultZone: http://eureka:eureka123@localhost:8761/eureka/
  server:
    enable-self-preservation: false # Disable self-preservation mode for development
    response-cache-update-interval-ms: 3000 # Response cache update interval
