server:
  port: 8761

spring:
  application:
    name: eureka-server

eureka:
  client:
    register-with-eureka: false  # Do not register itself
    fetch-registry: false  # Do not fetch registry
  server:
    enable-self-preservation: false  # For development, disable self-preservation
